import yfinance as yf
import pandas as pd
import pandas_ta as ta
import os
import warnings
warnings.filterwarnings('ignore')

os.makedirs('data', exist_ok=True)

# Define Nifty 100 Universe (Expand to all 100 in production)
NIFTY_100 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "BAJFINANCE.NS"
]

def build_dataset():
    all_data = []
    print("Phase 1: Downloading max historical data and building features...")
    
    for ticker in NIFTY_100:
        try:
            print(f"Processing {ticker}...")
            df = yf.download(ticker, period="max", progress=False)
            if df.empty or len(df) < 500:
                continue
            
            # Massive Feature Engineering
            df.ta.strategy("All") 
            
            # Drop purely forward-looking indicators generated by ta.strategy
            cols_to_drop = [c for c in df.columns if 'future' in c.lower()]
            df.drop(columns=cols_to_drop, inplace=True, errors='ignore')
            
            # Target creation: Did the stock jump >= 20% in the next 21 trading days (1 month)?
            df['Future_Return'] = df['Close'].shift(-21) / df['Close'] - 1
            df['Target'] = (df['Future_Return'] >= 0.20).astype(int)
            df['Ticker'] = ticker
            
            all_data.append(df.dropna())
        except Exception as e:
            print(f"Failed {ticker}: {e}")
            
    master_df = pd.concat(all_data)
    master_df.sort_index(inplace=True) # Sort chronologically for walk-forward
    
    # Save to Parquet format (much faster and smaller than CSV for ML datasets)
    master_df.to_parquet('data/nifty100_features.parquet')
    print(f"Data saved successfully. Total rows: {len(master_df)}, Total Features: {len(master_df.columns)}")

if __name__ == "__main__":
    build_dataset()
