import yfinance as yf
import pandas as pd
import pandas_ta as ta
import numpy as np
import lightgbm as lgb
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import log_loss, precision_score
import optuna
import shap
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings('ignore')

# Setup directories
os.makedirs('models', exist_ok=True)
os.makedirs('reports', exist_ok=True)

# 1. Define Nifty 100 Universe (Sample subset for brevity, add all 100 in production)
NIFTY_100 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "BAJFINANCE.NS",
    "TATASTEEL.NS", "ADANIENT.NS", "MARUTI.NS", "TATAMOTORS.NS", "M&M.NS"
]

def prepare_data():
    all_data = []
    print("Fetching max historical data and building feature space...")
    for ticker in NIFTY_100:
        try:
            df = yf.download(ticker, period="max", progress=False)
            if df.empty or len(df) < 500:
                continue
            
            # Massive Feature Engineering (MACD, RSI, BBANDS, ATR, etc.)
            df.ta.strategy("All") # Generates ~150-200 technical indicators
            
            # Drop purely forward-looking indicators generated by ta.strategy
            cols_to_drop = [c for c in df.columns if 'future' in c.lower()]
            df.drop(columns=cols_to_drop, inplace=True, errors='ignore')
            
            # Target creation: Did the stock jump >= 20% in the next 21 trading days (1 month)?
            df['Future_Return'] = df['Close'].shift(-21) / df['Close'] - 1
            df['Target'] = (df['Future_Return'] >= 0.20).astype(int)
            
            df['Ticker'] = ticker
            all_data.append(df.dropna())
        except Exception as e:
            print(f"Failed {ticker}: {e}")
            
    master_df = pd.concat(all_data)
    # Sort by date to prevent future leak in Walk-Forward
    master_df.sort_index(inplace=True) 
    return master_df

def walk_forward_optimization(df):
    features = [c for c in df.columns if c not in ['Target', 'Future_Return', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Volume']]
    X = df[features]
    y = df['Target']
    
    print(f"Total features created: {len(features)}")
    print(f"Total historical data points: {len(df)}")
    print(f"Class imbalance (Target = 1): {y.mean()*100:.2f}%")

    # TimeSeriesSplit for Walk-Forward testing (5 splits)
    tscv = TimeSeriesSplit(n_splits=5)
    
    def objective(trial):
        params = {
            'objective': 'binary',
            'metric': 'binary_logloss',
            'boosting_type': 'gbdt',
            'learning_rate': trial.suggest_float('learning_rate', 1e-3, 0.1, log=True),
            'num_leaves': trial.suggest_int('num_leaves', 20, 300),
            'max_depth': trial.suggest_int('max_depth', 3, 15),
            'feature_fraction': trial.suggest_float('feature_fraction', 0.3, 1.0),
            'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 50, 500),
            'pos_bagging_fraction': trial.suggest_float('pos_bagging_fraction', 0.5, 1.0),
            'neg_bagging_fraction': trial.suggest_float('neg_bagging_fraction', 0.1, 0.8),
            'verbose': -1
        }
        
        cv_scores = []
        for train_idx, test_idx in tscv.split(X):
            X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
            y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
            
            train_data = lgb.Dataset(X_train, label=y_train)
            test_data = lgb.Dataset(X_test, label=y_test, reference=train_data)
            
            gbm = lgb.train(
                params,
                train_data,
                num_boost_round=1000,
                valid_sets=[test_data],
                callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=False)]
            )
            preds = gbm.predict(X_test)
            cv_scores.append(log_loss(y_test, preds))
            
        return np.mean(cv_scores)

    print("Running Bayesian Optimization for exactly 1 Hour (3600 seconds)...")
    study = optuna.create_study(direction='minimize')
    # RUN FOR 1 HOUR
    study.optimize(objective, timeout=3600, n_jobs=-1)
    
    print("Best parameters found:")
    print(study.best_params)
    
    # Train final model on full dataset using best params
    final_params = study.best_params
    final_params.update({'objective': 'binary', 'verbose': -1})
    train_data = lgb.Dataset(X, label=y)
    final_model = lgb.train(final_params, train_data, num_boost_round=500)
    
    final_model.save_model('models/momentum_model.txt')
    
    # SHAP Explainability - "What happens before momentum?"
    print("Extracting Pre-Momentum Setup Rules via SHAP...")
    explainer = shap.TreeExplainer(final_model)
    shap_values = explainer.shap_values(X)
    
    plt.figure(figsize=(12, 8))
    shap.summary_plot(shap_values[1] if isinstance(shap_values, list) else shap_values, X, show=False)
    plt.savefig('reports/shap_momentum_setup.png', bbox_inches='tight')
    plt.close()
    print("SHAP plot saved. The top features shown on the right (high SHAP value) indicate the exact conditions prior to a 20%+ breakout.")

if __name__ == "__main__":
    df = prepare_data()
    walk_forward_optimization(df)
